### ISSUE TITLE
Nothing downloads in .cache/manga-cli/ and then EOF

### ISSUE THREAD

**Issue by Doge222222** [prsh11/manga-cli#17]
so I do in my home directory
$ manga-cli
Search manga: chainsaw man
[1]Chainsaw Man
Enter Number: 1
Enter chapter number: 82
EOF

Nothing happens after this and ~/.cache/manga-cli is empty
Tested with a few different mangas, same thing every time

**Comment by prsh11** [comment]
I will look into it
