### ISSUE TITLE
zip and rm not working with " "

### ISSUE THREAD

**Issue by eduardomdc** [prsh11/manga-cli#19]
manga-cli was giving out 
"error: could not open document"
I figured it was because rm and zip was not working properly with the arguments $image_dir enclosed by " in the create_file() function
```
zip -q $image_dir$name-$chapterNumber.cbz $image_dir*.jpg
rm $image_dir/*.jpg
```
works fine for me.

**Comment by lasmate** [comment]
can confirm this fix works perfectly
