### ISSUE TITLE
Enter Option: error: could not open document

### ISSUE THREAD

**Issue by purashy** [prsh11/manga-cli#29]
Hello,

I have a similar issue to #10 

I have all dependencies installed, however i keep receiving:
```
Enter Option: error: could not open document
```

**Comment by prsh11** [comment]
Which pdf viewer are you using?

**Comment by prsh11** [comment]
Probably try opening with another pdf viewer using 
```bash
manga-cli -o <your pdf viewer> 
```

**Comment by prsh11** [comment]
It works fine for me, but I can't understand why it is not working for you. Could you try a clean install?
```bash
rm /usr/local/bin/manga-cli
rm -rf ~/.cache/manga-cli
```

**Comment by prsh11** [comment]
Can check the list of the contents of `~/.cache/manga-cli` after trying to download a manga.

**Comment by prsh11** [comment]
can you send the code was the manga-cli file

**Comment by prsh11** [comment]
Do you have zip and Imagemagick installed?
