### ISSUE TITLE
No manga found

### ISSUE THREAD

**Issue by KitsuneKode** [prsh11/manga-cli#31]
`❯ manga-cli
Search manga: One Piece
EOF
EOF
Enter Number: 
`

`(zathura:250973): Gtk-WARNING **: 22:09:06.574: Theme parsing error: gtk.css:3213:16: Unit is missing.
info: Opening plain database via sqlite backend.
warning: sqlite database already exists. Set your database backend to sqlite
error: could not open document
`

Currently using 
 ​​  OS : Arch Linux x86_64 
   Kernel : 6.6.28-1-lts

**Comment by prsh11** [comment]
Check if you have dependencies installed. It is working for me. 
Try reinstalling if all the dependencies are installed.
